### ISSUE TITLE
alameda rolling update would fail when storageclass is rook-ceph-block, unable to mount volumes 

### ISSUE THREAD

**Issue by jeantung** [containers-ai/federatorai-operator#173]
[Steps]
1.Edit federatorai-operator yaml image version from 0.2.2 to 0.2.3, and make sure new pod is running.
2."oc edit alamedaservice -n federatorai" to edit version from 0.3.10 to 0.3.11, and check to see if all alameda pods are running well.

[Actaul Results]
admission-controller-5859b59674-8dnfw
alameda-ai-f9cc69d77-m5jnh
alameda-datahub-5cb574c87f-lwnz5
alameda-evictioner-6c868d8857-5s9ch
alameda-operator-5fc5bb49c9-6q5sw
Those pods are status: ContainerCreating, and message like "MountVolume.SetUp failed for volume "pvc-1ef23ef3-7d32-11e9-9a22-00505698e965" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume pvc-1ef23ef3-7d32-11e9-9a22-00505698e965 for pod federatorai/alameda-evictioner-6c868d8857-5s9ch. Volume is already attached by pod federatorai/alameda-evictioner-c85f54f4b-cptg8. Status Running"
[](url)
[Environment]
master: 172.31.12.27 root/password
node: 172.31.12.28 root/password
storageclass: rook-ceph-block
![Image 1](https://user-images.githubusercontent.com/38522441/58445294-b3691d80-812e-11e9-902f-69910ce4688a.png)
![Image 2](https://user-images.githubusercontent.com/38522441/58445295-b3691d80-812e-11e9-9f3a-7c1f7fba45f8.png)

**Comment by kfdev170707** [comment]
Due to AlamedaService uses rolling update strategy in deployment, new pod and legacy pod try to mount the same volume at the same time. According to [Ceph Storage](https://rook.io/docs/rook/v0.8/storage.html), **the block storage mount to only one pod at a time**.
To resolve the issue, please try using Shared File System instead of Block Storage as persistent volume storage.

References:
1. [Create the File System](https://rook.io/docs/rook/v0.8/filesystem.html)
2. [Consuming storage using FlexVolume drivers](https://docs.okd.io/latest/install_config/persistent_storage/persistent_storage_flex_volume.html#flex-volume-usage)

**Comment by jeantung** [comment]
Verified.
